export const ADD_DEVELOPER_REQUEST = 'ADD_DEVELOPER_REQUEST';
export const ADD_DEVELOPER_SUCCESS = 'ADD_DEVELOPER_SUCCESS';
export const ADD_DEVELOPER_FAILED = 'ADD_DEVELOPER_FAILED';

export const ADD_MANAGER_REQUEST = 'ADD_MANAGER_REQUEST';
export const ADD_MANAGER_SUCCESS = 'ADD_MANAGER_SUCCESS';
export const ADD_MANAGER_FAILED = 'ADD_MANAGER_FAILED';

export const ADD_PROJECT_REQUEST = 'ADD_PROJECT_REQUEST';
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS';
export const ADD_PROJECT_FAILED = 'ADD_PROJECT_FAILED';

export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const UPDATE_MANAGER = 'UPDATE_MANAGER';
export const UPDATE_DEVELOPER = 'UPDATE_DEVELOPER';

export const REMOVE_PROJECT = 'REMOVE_PROJECT';
export const REMOVE_MANAGER = 'REMOVE_MANAGER';
export const REMOVE_DEVELOPER = 'REMOVE_DEVELOPER';

export const CHOOSED_EASY = 'CHOOSED_EASY';
export const CHOOSED_MEDIUM = 'CHOOSED_MEDIUM';
export const CHOOSED_HARD = 'CHOOSED_HARD';

export const HIRE_MANAGER = 'HIRE_MANAGER';
export const HIRE_DEVELOPER = 'HIRE_DEVELOPER';

export const FIRE_MANAGER = 'FIRE_MANAGER';
export const FIRE_DEVELOPER = 'FIRE_DEVELOPER';

export const FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAILED = 'FETCH_PROJECTS_FAILED';

export const FETCH_MANAGERS_REQUEST = 'FETCH_MANAGERS_REQUEST';
export const FETCH_MANAGERS_SUCCESS = 'FETCH_MANAGERS_SUCCESS';
export const FETCH_MANAGERS_FAILED = 'FETCH_MANAGERS_FAILED';

export const FETCH_DEVELOPERS_REQUEST = 'FETCH_DEVELOPERS_REQUEST';
export const FETCH_DEVELOPERS_SUCCESS = 'FETCH_DEVELOPERS_SUCCESS';
export const FETCH_DEVELOPERS_FAILED = 'FETCH_DEVELOPERS_FAILED';

export const GET_SALARY = 'GET_SALARY';
export const PROJECT_COMPLETED = 'PROJECT_COMPLETED';

export const START = 'START';
export const STOP = 'STOP';
export const GET_COMPANY_NAME = 'GET_COMPANY_NAME';
export const TICK_GAME = 'TICK_GAME';
export const ERROR = 'ERROR';
